// apps/partner-svelte/src/lib/components/SupportChat.svelte
<script lang="ts">
  import type { ChatWidgetTheme } from "@pulse/embed";

  import { createChatAttachment } from "../helpers/chat-attachment";
  import { getApiUrl } from "../helpers/config";
  import { createPartnerClient } from "../helpers/demo-client";

  let error: string | null = $state(null);
  const theme = {
    colors: {
      background: "#fffaf5",
      border: "#e7d5c5",
      muted: "#806957",
      primary: "#b83b12",
      surface: "#f7eee5",
      text: "#38261b",
    },
    fontFamily: '"Trebuchet MS", ui-sans-serif, system-ui, sans-serif',
    preset: "light",
    radius: "16px",
  } as const satisfies ChatWidgetTheme;

  const attachChat = createChatAttachment({
    createClient: () => createPartnerClient(getApiUrl()),
    theme,
    onError: () => {
      error = "Could not load the chat. Reload to try again.";
    },
  });
</script>

{#if error}
  <p role="alert">{error}</p>
{/if}
<pulse-chat {@attach attachChat} room-id="demo-room"></pulse-chat>

// apps/partner-vue/src/components/SupportChat.vue
<script setup lang="ts">
import "@pulse/embed";
import type { ChatWidgetTheme, PulseChatElement } from "@pulse/embed";
import { onBeforeUnmount, onMounted, useTemplateRef } from "vue";

import { getApiUrl } from "../helpers/config";
import { createPartnerClient } from "../helpers/demo-client";

const chat = useTemplateRef<PulseChatElement>("chat");
const client = createPartnerClient(getApiUrl());
const theme = {
  colors: {
    background: "#fff9ff",
    border: "#d9c8ff",
    muted: "#715e83",
    primary: "#7447f5",
    surface: "#f4ecff",
    text: "#27183b",
  },
  fontFamily:
    '"Avenir Next", Avenir, "Trebuchet MS", ui-sans-serif, system-ui, sans-serif',
  preset: "light",
  radius: "28px",
} as const satisfies ChatWidgetTheme;

onMounted(() => {
  if (!chat.value) return;
  chat.value.client = client;
  chat.value.theme = theme;
});

onBeforeUnmount(() => client.dispose());
</script>

<template>
  <pulse-chat ref="chat" room-id="demo-room" />
</template>
